### ISSUE TITLE
Only works in preview

### ISSUE THREAD

**Issue by svallory** [MamoruDS/obsidian-open-link-with#3]
Hi, thanks for the cool plugin!

I noticed that clicking on links in edit mode does not open them in the selected browser

I'm using the latest version of Obsidian on a Mac

**Comment by MamoruDS** [comment]
Hi, sorry for the late reply to you. 

This plugin currently only works in preview mode, and I agree that it needs to work in edit mode as well. But after some attempts, I found it kinda different. In my attempts, the web page opens in both the default browser and the browser configured in the plugin simultaneously after clicking(with modifier key) on the link. 

The principle behind this is that the link in edit mode is actually not a hyperlink, obsidian using inner function to handle the click event, which is unable to be hijacked(or disabled) by the plugin. So this function can be implemented, but in a broken way. The alternative solution is to use a different modifier (alt or shift) to start the click event, but this can feel strange and cause potential conflict problems.

Anyway, I'll add the modifier method to the plugin, at least it's better than not having it at all.

**Comment by MamoruDS** [comment]
By upgrading the plugin to version `0.1.4`, the browser's override behavior will work properly in edit mode.

**Comment by XMB-7** [comment]
@MamoruDS
With the version `0.1.5`, this plugin seems that still only works in preview mode, and it would prevent opening links in edit mode.
![图片](https://user-images.githubusercontent.com/65625632/167337482-14931a52-3a05-4295-bf2e-7f44b8ab4537.png)
![图片](https://user-images.githubusercontent.com/65625632/167337443-d0e8b3cb-7463-4abb-8b1f-2f35bae8c706.png)
Could you help to check that? Not sure if it is a personal problem. BTW, thanks for building this cool plugin.

**Comment by BellTseng** [comment]
@MamoruDS  
Thanks for your plugins!
Same problem that could not opening links in edit mode(live preview), but I solved it by adding some code based on your main.js code. 
I just learned js,  maybe there are some bugs. Share with you @XMB-7. you can try it!
<img width="724" alt="image" src="https://user-images.githubusercontent.com/38106775/171227316-8e61114a-f234-43d6-99f8-7d9cc08520c1.png">
<img width="746" alt="image" src="https://user-images.githubusercontent.com/38106775/171227415-f8f07ee5-cef2-4c70-97af-68e18175fa76.png">

**Comment by Kyubendo** [comment]
Still doesn't work in the preview mode.
Version 0.1.8.

**Comment by matteobrusa** [comment]
+1

**Comment by sjerdmann** [comment]
Hi,
I confirm clicking on links directly has no effect in live preview. However, I noticed that unwrapping the link (with `Alt + Click`) to show the URL and clicking on the URL does open it, whereas it should not (at least, it does not without the plugin). I'm really no JS specialist, but maybe the event is captured at the wrong moment or something ?...
Thanks for the plugin anyway !

**Comment by MamoruDS** [comment]
I believe I have a solution to this issue. The root cause of this problem is my insufficient study of Obsidian click actions, from my testing, Obsidian's click actions can be summarized in the following table:

| Ctrl | Alt | Shift | Edit                                  | Edit (live)                           | Read              |
| ---- | --- | ----- | ------------------------------------- | ------------------------------------- | ----------------- |
|      |     |       | <span style="color:red">cursor</span> | open                                  | open              |
| 🖱️   |     |       | open                                  | open (new panel)                      | open (new panel)  |
|      | 🖱️  |       | <span style="color:red">cursor</span> | <span style="color:red">cursor</span> | open              |
|      |     | 🖱️    | <span style="color:red">cursor</span> | <span style="color:red">cursor</span> | open              |
| 🖱️   | 🖱️  |       | open (new split)                      | open (new split)                      | open (new split)  |
| 🖱️   |     | 🖱️    | open (new panel)                      | open (new panel)                      | open (new panel)  |
|      | 🖱️  | 🖱️    | <span style="color:red">cursor</span> | <span style="color:red">cursor</span> | open              |
| 🖱️   | 🖱️  | 🖱️    | open (new window)                     | open (new window)                     | open (new window) |

The appropriate implementation should follow Obsidian's default click behaviors, I will give a quick fix on this

**Comment by MamoruDS** [comment]
Hey, I just released version 0.1.9 of this plugin which should fix the issue of links not working in live preview mode. And also, if you're using an in-app view as your link opener, all modifiers (combinations) should now work like in Obsidian's default. But keep in mind that, since the plugin's current setting only support one modifier binding and modifiers can be combined in different ways, I'll make it more flexible in the future version. Also, some custom modifier bindings won't work in this version since they are used for cursor move/selection which are treated as non-clickable. Please let me know if there are any other issues

**Comment by matteobrusa** [comment]
Fix confirmed, thanks for the great work!

**Comment by sjerdmann** [comment]
It works great indeed, thanks a lot !
